# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Server'),
        ),
        migrations.AlterField(
            model_name='race',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faction'),
        ),
        migrations.AlterField(
            model_name='race',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Game'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='spec_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SpecType'),
        ),
        migrations.DeleteModel(
            name='Faction',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='SpecType',
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='player.Player'),
        ),
        migrations.AddField(
            model_name='playerfeedback',
            name='to_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_player', to='player.Player'),
        ),
    ]
