# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='/boss/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('lvl', models.IntegerField(blank=True, null=True)),
                ('health', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DifficultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('lvl', models.IntegerField(blank=True, null=True)),
                ('difficult_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.DifficultType')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.Game')),
            ],
        ),
        migrations.CreateModel(
            name='RaidGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.Game')),
            ],
        ),
        migrations.CreateModel(
            name='RaidGroupAvaliable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.Boss')),
                ('difficult_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.DifficultType')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.Game')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.Raid')),
                ('raid_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.RaidGroup')),
            ],
        ),
        migrations.AddField(
            model_name='raidgroup',
            name='raids',
            field=models.ManyToManyField(through='raid.RaidGroupAvaliable', to='raid.Raid'),
        ),
        migrations.AddField(
            model_name='boss',
            name='difficult_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raid.DifficultType'),
        ),
    ]
